/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Simulador;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import Modelo.Archivo;
import java.util.Enumeration;

/**
 *
 * @author Arturo
 */
public class CrearNodo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearNodo.class.getName());

    private DefaultTreeModel modelo;
    private Simulador Gestor;
    
    public CrearNodo(DefaultTreeModel modeloArbol, Simulador Gestor) {
        initComponents();
        this.Gestor = Gestor;
        this.setSize(560, 360);
        this.setResizable(false);
        ListaPadres.removeAllItems();
        this.modelo = modeloArbol;
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
        this.cargarNodosRecursivo(raiz);
        SelectedField.setText(raiz.toString());
    }
    
    private void cargarNodosRecursivo(DefaultMutableTreeNode nodo) {
        
        if (!nodo.isLeaf()){
        ListaPadres.addItem(nodo.toString());
        }
        // Si tiene hijos, recorremos los hijos también
        if (nodo.getChildCount() > 0) {
            for (int i = 0; i < nodo.getChildCount(); i++) {
                DefaultMutableTreeNode hijo = (DefaultMutableTreeNode) nodo.getChildAt(i);
                cargarNodosRecursivo(hijo);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ListaPadres = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        SelectedField = new javax.swing.JLabel();
        SelectParent = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TypeChanger = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        SizeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        ListaPadres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Agregar a:");

        SelectedField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SelectedField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectedField.setText("raiz");

        SelectParent.setText("Seleccionar");
        SelectParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectParentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaPadres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SelectedField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SelectParent)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectedField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ListaPadres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectParent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Label.setText("Nuevo Archivo");

        jLabel3.setText("Nombre");

        TypeChanger.setText("Archivo");
        TypeChanger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeChangerActionPerformed(evt);
            }
        });

        jLabel2.setText("Cambiar tipo");

        CreateButton.setText("Crear");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        BackButton.setText("X");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        NameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameFieldKeyTyped(evt);
            }
        });

        jLabel1.setText("Tamaño (Bloques)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 63, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CreateButton)
                            .addComponent(Label))
                        .addGap(35, 35, 35)
                        .addComponent(BackButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TypeChanger)
                            .addComponent(SizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TypeChanger)
                .addGap(57, 57, 57)
                .addComponent(CreateButton)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectParentActionPerformed
     
    
    SelectedField.setText(ListaPadres.getSelectedItem().toString());
        
        
        
    }//GEN-LAST:event_SelectParentActionPerformed

    private void TypeChangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeChangerActionPerformed
       
        if (TypeChanger.getText().equals("Archivo")) {
          TypeChanger.setText("Directorio");  
        } else {
            TypeChanger.setText("Archivo"); 
        }
        
        
        
        
        Label.setText("Nuevo " + TypeChanger.getText());
        
        
    }//GEN-LAST:event_TypeChangerActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        
        
        String TamañoTexto = SizeTextField.getText(); // Imagina que esto viene de tu JTextField
        int TamañoNumero; 

        Archivo auxiliar = this.Gestor.SD.buscarPorNombre(NameField.getText());
         if (auxiliar != null)  {
             return;
         } 
try {
    TamañoNumero = Integer.parseInt(TamañoTexto.trim());
  
} catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
            "El valor ingresado no es un número válido. Por favor escribe solo dígitos.",
            "Error de formato",
            javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
}

        boolean EsDirectorio;

        
        if (TypeChanger.getText().equals("Archivo")) {
            EsDirectorio = false;
        } else {
            EsDirectorio = true;
        }
        
        Archivo archivo = new Archivo(NameField.getText(),EsDirectorio,TamañoNumero);
        
        
        
        
        DefaultMutableTreeNode NuevoNodo = new DefaultMutableTreeNode(archivo.getNombre(),EsDirectorio);
        DefaultMutableTreeNode Padre = buscarNodoPorNombre(SelectedField.getText());
        int indice = Padre.getChildCount();
        modelo.insertNodeInto(NuevoNodo, Padre, indice);
        
        Gestor.SD.insertarArch(archivo);
        this.dispose();
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameFieldKeyTyped
             // 1. Obtenemos el carácter que el usuario acaba de teclear
    char c = evt.getKeyChar();

    // 2. Verificamos si NO es una letra Y tampoco es un espacio
    // (Añade más condiciones si necesitas permitir algo más)
    if (!Character.isLetter(c) && c != ' ') {
        
        // 3. "Consumimos" el evento para que no se procese (no se escribe)
        evt.consume();
        
        // Opcional: Emitir un pitido para avisar al usuario
        java.awt.Toolkit.getDefaultToolkit().beep();
    }
    }//GEN-LAST:event_NameFieldKeyTyped

    
    public DefaultMutableTreeNode buscarNodoPorNombre(String nombreBuscado) {
    // 1. Obtener la raíz del árbol
    DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
    
    // 2. Crear una enumeración para recorrer todo el árbol (Búsqueda en anchura)
    Enumeration e = raiz.breadthFirstEnumeration();
    
    // 3. Recorrer todos los nodos
    while (e.hasMoreElements()) {
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) e.nextElement();
        
        // 4. Comparar el texto del nodo con lo que buscamos
        // Usamos equalsIgnoreCase para que no importen mayúsculas/minúsculas
        if (nodo.getUserObject().toString().equalsIgnoreCase(nombreBuscado)) {
            return nodo; // ¡Encontrado!
        }
    }
    
    return null; // No se encontró nada
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CreateButton;
    private javax.swing.JLabel Label;
    private javax.swing.JComboBox<String> ListaPadres;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton SelectParent;
    private javax.swing.JLabel SelectedField;
    private javax.swing.JTextField SizeTextField;
    private javax.swing.JButton TypeChanger;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
