/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import Controlador.Simulador;
import Modelo.DirectorioEntrada;
import java.util.Enumeration;
import javax.swing.JOptionPane;
import Modelo.Archivo;

/**
 *
 * @author Arturo
 */
public class CrearNodo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearNodo.class.getName());

    private DefaultTreeModel modelo;
    private Simulador gestorFS;
    
    public CrearNodo(DefaultTreeModel modeloArbol, Simulador gestor) {
        initComponents();
        this.setSize(560, 360);
        this.setResizable(false);
        ListaPadres.removeAllItems();
        this.modelo = modeloArbol;
        this.gestorFS = gestor;
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
        this.cargarNodosRecursivo(raiz);
        
        DirectorioEntrada raizData = (DirectorioEntrada) raiz.getUserObject(); 
        SelectedField.setText(raizData != null ? raizData.getNombre() : "Raiz");
    }
    
    private void cargarNodosRecursivo(DefaultMutableTreeNode nodo) {
        Object userObject = nodo.getUserObject();

        // Solo procesamos nodos que contienen nuestro modelo de datos real
        if (userObject instanceof DirectorioEntrada) {
            DirectorioEntrada entrada = (DirectorioEntrada) userObject;

            // Solo agregamos directorios a la lista de padres disponibles
            if (entrada.getEsDirectorio()){
                ListaPadres.addItem(entrada.getNombre());
            }
        }

        // Recorrer los hijos
        if (nodo.getChildCount() > 0) {
            for (int i = 0; i < nodo.getChildCount(); i++) {
                DefaultMutableTreeNode hijo = (DefaultMutableTreeNode) nodo.getChildAt(i);
                cargarNodosRecursivo(hijo);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ListaPadres = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        SelectedField = new javax.swing.JLabel();
        SelectParent = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TypeChanger = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        SizeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        ListaPadres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Agregar a:");

        SelectedField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SelectedField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectedField.setText("raiz");

        SelectParent.setText("Seleccionar");
        SelectParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectParentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaPadres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SelectedField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SelectParent)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectedField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ListaPadres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectParent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Label.setText("Nuevo Archivo");

        jLabel3.setText("Nombre");

        TypeChanger.setText("Archivo");
        TypeChanger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeChangerActionPerformed(evt);
            }
        });

        jLabel2.setText("Cambiar tipo");

        CreateButton.setText("Crear");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        BackButton.setText("X");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Tamaño (Bloques)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 63, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CreateButton)
                            .addComponent(Label))
                        .addGap(35, 35, 35)
                        .addComponent(BackButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TypeChanger)
                            .addComponent(SizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TypeChanger)
                .addGap(57, 57, 57)
                .addComponent(CreateButton)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectParentActionPerformed
     
    
    SelectedField.setText(ListaPadres.getSelectedItem().toString());
        
        
        
    }//GEN-LAST:event_SelectParentActionPerformed

    private void TypeChangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeChangerActionPerformed
       
        if (TypeChanger.getText().equals("Archivo")) {
          TypeChanger.setText("Directorio");  
        } else {
            TypeChanger.setText("Archivo"); 
        }
        
        
        
        
        Label.setText("Nuevo " + TypeChanger.getText());
        
        
    }//GEN-LAST:event_TypeChangerActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        
        
        String nombre = NameField.getText().trim();
        String tamañoTexto = SizeTextField.getText().trim();
        int tamañoNumero = 0;

        // 1. Validación de nombre
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Validación y obtención de tamaño
        try {
            tamañoNumero = Integer.parseInt(tamañoTexto);
            if (tamañoNumero < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
            "El tamaño (bloques) debe ser un número entero positivo.",
            "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Determinar el tipo y ajustar tamaño
        boolean esDirectorio = TypeChanger.getText().equals("Directorio");

        if (esDirectorio) {
            tamañoNumero = 0; // Los directorios no consumen bloques en esta simulación
        } else if (tamañoNumero == 0) {
            JOptionPane.showMessageDialog(this, "Los archivos deben tener un tamaño mayor a 0 bloques.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Buscar el nodo padre en el JTree y obtener su objeto de datos real (DirectorioEntrada)
        DefaultMutableTreeNode nodoPadreSwing = buscarNodoPorNombre(SelectedField.getText());
        if (nodoPadreSwing == null) {
            JOptionPane.showMessageDialog(this, "Error interno: No se encontró el directorio padre seleccionado.", "Error Interno", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DirectorioEntrada padreFS = (DirectorioEntrada) nodoPadreSwing.getUserObject();

        // 5. DELEGAR la creación al Simulador/AdministradorDirectorios
        // Usamos gestorFS para acceder a la lógica de negocio
        DirectorioEntrada nuevaEntradaFS = gestorFS.getAdminFS().crearEntrada(
            nombre, esDirectorio, tamañoNumero, padreFS, gestorFS.getTipoUsuario()
        );

        if (nuevaEntradaFS != null) {
            // 6. Si se creó correctamente, sincronizar el JTree
            // El nuevo nodo debe contener el objeto DirectorioEntrada real.
            DefaultMutableTreeNode nuevoNodoSwing = new DefaultMutableTreeNode(nuevaEntradaFS, esDirectorio);

            // El método insertNodeInto actualiza el modelo y el árbol automáticamente
            modelo.insertNodeInto(nuevoNodoSwing, nodoPadreSwing, nodoPadreSwing.getChildCount());
            modelo.reload(); 

            JOptionPane.showMessageDialog(this, "Entrada '" + nombre + "' creada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            // 7. Manejo de errores de negocio (espacio, duplicados, permisos)
            JOptionPane.showMessageDialog(this, "ERROR: No se pudo crear la entrada. Verifique el nombre, el espacio disponible en disco y los permisos.", "Error de Sistema de Archivos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_CreateButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_BackButtonActionPerformed

    
    public DefaultMutableTreeNode buscarNodoPorNombre(String nombreBuscado) {
    DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
    Enumeration e = raiz.breadthFirstEnumeration();
    
    while (e.hasMoreElements()) {
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) e.nextElement();
        Object userObject = nodo.getUserObject();

        if (userObject instanceof DirectorioEntrada) {
            DirectorioEntrada entrada = (DirectorioEntrada) userObject;
            
            // Compara el nombre del objeto DirectorioEntrada real
            if (entrada.getNombre().equalsIgnoreCase(nombreBuscado)) {
                return nodo; 
            }
        }
    }
    return null;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CreateButton;
    private javax.swing.JLabel Label;
    private javax.swing.JComboBox<String> ListaPadres;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton SelectParent;
    private javax.swing.JLabel SelectedField;
    private javax.swing.JTextField SizeTextField;
    private javax.swing.JButton TypeChanger;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
