/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.util.Enumeration;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Arturo
 */
public class ModificarNodo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModificarNodo.class.getName());

    private DefaultTreeModel modelo;
    private String NodoModificado;
    private String NuevoNombre;
    
    public ModificarNodo(DefaultTreeModel modeloArbol) {
        initComponents();
        
        this.setResizable(false);
        ListaNodos.removeAllItems();
        this.modelo = modeloArbol;
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
        this.cargarNodosRecursivo(raiz);
        OldNameLabel.setText(raiz.toString());
    }
    
    private void cargarNodosRecursivo(DefaultMutableTreeNode nodo) {
        
        
        ListaNodos.addItem(nodo.toString());
        
        // Si tiene hijos, recorremos los hijos también
        if (nodo.getChildCount() > 0) {
            for (int i = 0; i < nodo.getChildCount(); i++) {
                DefaultMutableTreeNode hijo = (DefaultMutableTreeNode) nodo.getChildAt(i);
                cargarNodosRecursivo(hijo);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ListaNodos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        OldNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonGuardar = new javax.swing.JButton();
        BotonCambiarNombre = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        NewNameTextField = new javax.swing.JTextField();
        SelectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        ListaNodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaNodosActionPerformed(evt);
            }
        });

        jLabel1.setText("ACTUAL");

        OldNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OldNameLabel.setText("Antiguo nombre");
        OldNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("AHORA");

        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonCambiarNombre.setText("Modificar");
        BotonCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCambiarNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("CAMBIAR NOMBRE");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BackButton.setText("X");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        NewNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewNameTextFieldActionPerformed(evt);
            }
        });
        NewNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NewNameTextFieldKeyTyped(evt);
            }
        });

        SelectButton.setText("✓");
        SelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ListaNodos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(SelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OldNameLabel)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonCambiarNombre)
                                .addGap(47, 47, 47)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(BotonGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaNodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(SelectButton))
                .addGap(2, 2, 2)
                .addComponent(OldNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonCambiarNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaNodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaNodosActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        
        
    DefaultMutableTreeNode NodoModificado = buscarNodoPorNombre(this.NodoModificado);
    
    
    
    NodoModificado.setUserObject(NuevoNombre);
    modelo.nodeChanged(NodoModificado);
        this.dispose();
        
    }//GEN-LAST:event_BotonGuardarActionPerformed

   public DefaultMutableTreeNode buscarNodoPorNombre(String nombreBuscado) {
    // 1. Obtener la raíz del árbol
    DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
    
    // 2. Crear una enumeración para recorrer todo el árbol (Búsqueda en anchura)
    Enumeration e = raiz.breadthFirstEnumeration();
    
    // 3. Recorrer todos los nodos
    while (e.hasMoreElements()) {
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) e.nextElement();
        
        // 4. Comparar el texto del nodo con lo que buscamos
        // Usamos equalsIgnoreCase para que no importen mayúsculas/minúsculas
        if (nodo.getUserObject().toString().equalsIgnoreCase(nombreBuscado)) {
            return nodo; // ¡Encontrado!
        }
    }
    
    return null; // No se encontró nada
}
    
    
    private void BotonCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCambiarNombreActionPerformed
       
    this.NuevoNombre = NewNameTextField.getText();
        
     OldNameLabel.setText(NuevoNombre);
     
        
        
    }//GEN-LAST:event_BotonCambiarNombreActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NewNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewNameTextFieldActionPerformed
        
    }//GEN-LAST:event_NewNameTextFieldActionPerformed

    private void SelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButtonActionPerformed
        
        this.NodoModificado = ListaNodos.getSelectedItem().toString();
        OldNameLabel.setText(NodoModificado);
        
        
    }//GEN-LAST:event_SelectButtonActionPerformed

    private void NewNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NewNameTextFieldKeyTyped
        // 1. Obtenemos el carácter que el usuario acaba de teclear
    char c = evt.getKeyChar();

    // 2. Verificamos si NO es una letra Y tampoco es un espacio
    // (Añade más condiciones si necesitas permitir algo más)
    if (!Character.isLetter(c) && c != ' ') {
        
        // 3. "Consumimos" el evento para que no se procese (no se escribe)
        evt.consume();
        
        // Opcional: Emitir un pitido para avisar al usuario
        java.awt.Toolkit.getDefaultToolkit().beep();
    }
    }//GEN-LAST:event_NewNameTextFieldKeyTyped

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BotonCambiarNombre;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JComboBox<String> ListaNodos;
    private javax.swing.JTextField NewNameTextField;
    private javax.swing.JLabel OldNameLabel;
    private javax.swing.JButton SelectButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
